version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: shortener_db_postgres
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: shortener_url
    ports:
      - "5433:5432"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


# postgresql://test_user:test_password@localhost:5433/shortener_db
# 
# go run ./cmd/migrate up